### ISSUE TITLE
duplicate topics for #eng-brew-build-complete in the doc

### ISSUE THREAD

**Issue by matt8754** [release-engineering/fedmsg_meta_umb#31]
There are two entries for #eng-brew-build-complete in 

https://datagrepper-prod-datanommer.int.open.paas.redhat.com/umb/topics.html

It seems like the topic of the test class "TestBrewBuildCompleteDocker" is wrong. Right now, it is ''/topic/VirtualTopic.eng.brew.build.complete', but I guess it should be  ''/topic/VirtualTopic.eng.brew.build.complete.docker'.

**Comment by ralphbean** [comment]
First - the topic for that one docker build is actually right. It's just brew.build.complete.

I think the issue here really is just that we're missing docstrings for the brew tests.  They provide a little more info to the reader where we can explain that it is normal to expect more than one example for some topics in the docs (if there are substantially different examples, for instance).

**Comment by matt8754** [comment]
Aha, I see. I did not realize that there could be more than one example for the same topic.
